
services:
  fhir:
    container_name: fhir
    image: "hapiproject/hapi:latest"
    ports:
      - "8080:8080"
    configs:
      - source: hapi
        target: /app/config/application.yaml
    depends_on:
      - db
    networks:
      - hapi-starter

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hapi
    volumes:
      - ./hapi.postgres.data:/var/lib/postgresql/data
    networks:
      - hapi-starter

configs:
  hapi:
     file: ./hapi.application.yaml

networks:
  hapi-starter: